version: '3.8'

services:
  client:
    image: himashachinthani/plant_store_frontend:latest
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://54.85.27.252:5000
    stdin_open: true
    tty: true
    depends_on:
      - server
    networks:
      - plant_network

  server:
    image: himashachinthani/plant_store_backend:latest
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_PORT=3306
      - DB_NAME=plant_store
      - JWT_SECRET=GreenNestPlantsSecretKey2026!
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server/uploads:/app/uploads
    networks:
      - plant_network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: plant_store
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./server/migrations:/docker-entrypoint-initdb.d
    networks:
      - plant_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  plant_network:
    driver: bridge

volumes:
  db_data:
